import { describe, expect, it, vi } from "vitest";
import { restoreNameLookups, stampOf } from "./name-lookups.mjs";

const stubTarget = "../run/systemd/resolve/stub-resolv.conf";
const tailscaleFile = "# resolv.conf(5) file generated by tailscale\nnameserver 100.100.100.100\n";

/**
 * /etc as a map: a path is a file { content, mode } or a link { target }. Lookups work only while
 * /etc/resolv.conf is the stub link, which is how the owner's server behaved - unless `stubWorks`
 * says the stub itself is broken, for the rollback.
 */
function fakeHost({ conf = { content: tailscaleFile }, stubFile = true, resolved = "active", stubAnswers = true, stubWorks = true } = {}) {
  const paths = new Map([["/etc/resolv.conf", conf]]);
  if (conf === null) paths.delete("/etc/resolv.conf");
  const error = (code) => Object.assign(new Error(code), { code });
  const files = {
    readlink: vi.fn(async (file) => { const entry = paths.get(file); if (!entry) throw error("ENOENT"); if (!("target" in entry)) throw error("EINVAL"); return entry.target; }),
    readFile: vi.fn(async (file) => { const entry = paths.get(file); if (!entry) throw error("ENOENT"); return "target" in entry ? "nameserver 127.0.0.53\n" : entry.content; }),
    isFile: vi.fn(async () => stubFile),
    copyFile: vi.fn(async (from, to) => { if (paths.has(to)) throw error("EEXIST"); const entry = paths.get(from); if (!entry) throw error("ENOENT"); paths.set(to, { ...entry }); }),
    symlink: vi.fn(async (target, file) => { if (paths.has(file)) throw error("EEXIST"); paths.set(file, { target }); }),
    rename: vi.fn(async (from, to) => { const entry = paths.get(from); if (!entry) throw error("ENOENT"); paths.delete(from); paths.set(to, entry); }),
    unlink: vi.fn(async (file) => { if (!paths.delete(file)) throw error("ENOENT"); }),
  };
  const linked = () => paths.get("/etc/resolv.conf")?.target === stubTarget;
  const run = vi.fn(async (binary, args) => {
    const name = binary.split("/").pop();
    if (name === "systemctl") return { ok: resolved === "active", code: 0, stdout: resolved, stderr: "" };
    if (name === "getent") return linked() && stubWorks ? { ok: true, code: 0, stdout: `192.0.2.10 STREAM ${args[1]}\n`, stderr: "" } : { ok: false, code: 2, stdout: "", stderr: "" };
    throw new Error(`unexpected ${binary}`);
  });
  const ask = vi.fn(async () => (stubAnswers ? { ok: true, addresses: ["192.0.2.10"], error: null } : { ok: false, addresses: [], error: "ETIMEOUT" }));
  return { paths, files, run, ask, sleep: async () => {} };
}

const now = () => new Date("2026-09-29T22:18:04.512Z");

describe("Point name lookups back to systemd-resolved", () => {
  it("stamps the copy it keeps sortably", () => {
    expect(stampOf(now())).toBe("20260929T221804Z");
  });

  it("does what the owner did by hand: keeps Tailscale's file, links the stub, and names resolve", async () => {
    const host = fakeHost();
    const lines = [];
    const result = await restoreNameLookups({}, { ...host, now, log: (line) => lines.push(line) });
    expect(result).toMatchObject({ changed: true, backup: "/etc/resolv.conf.boxpilot-20260929T221804Z", previous: { kind: "file", nameservers: ["100.100.100.100"] } });
    expect(host.paths.get("/etc/resolv.conf")).toEqual({ target: stubTarget });
    expect(host.paths.get("/etc/resolv.conf.boxpilot-20260929T221804Z")).toEqual({ content: tailscaleFile });
    // Swapped in with one rename, from a temporary link beside it: never a moment without the file.
    expect(host.files.rename).toHaveBeenCalledWith("/etc/.resolv.conf.boxpilot-20260929T221804Z.new", "/etc/resolv.conf");
    expect([...host.paths.keys()].filter((file) => file.endsWith(".new"))).toEqual([]);
    expect(lines.join("\n")).toContain("Tailscale was not restarted");
  });

  it("never keeps its copy over an earlier one: two runs in one second share a stamp", async () => {
    // As two runs within a second on the CI runner did: the second's copy failed with EEXIST.
    const host = fakeHost();
    host.paths.set("/etc/resolv.conf.boxpilot-20260929T221804Z", { content: "an earlier copy\n" });
    const result = await restoreNameLookups({}, { ...host, now });
    expect(result.backup).toBe("/etc/resolv.conf.boxpilot-20260929T221804Z-2");
    expect(host.paths.get("/etc/resolv.conf.boxpilot-20260929T221804Z")).toEqual({ content: "an earlier copy\n" });
    expect(host.paths.get("/etc/resolv.conf.boxpilot-20260929T221804Z-2")).toEqual({ content: tailscaleFile });
    // A copy that cannot be made at all stops it before anything changes.
    const full = fakeHost();
    full.files.copyFile.mockImplementationOnce(async () => { throw Object.assign(new Error("ENOSPC"), { code: "ENOSPC" }); });
    await expect(restoreNameLookups({}, { ...full, now })).rejects.toThrow("A copy of /etc/resolv.conf could not be kept (ENOSPC), so nothing was changed.");
    expect(full.paths.get("/etc/resolv.conf")).toEqual({ content: tailscaleFile });
  });

  it("keeps a link as a link", async () => {
    const host = fakeHost({ conf: { target: "/run/tailscale/resolv.conf" } });
    const result = await restoreNameLookups({}, { ...host, now });
    expect(result).toMatchObject({ changed: true, previous: { kind: "link", target: "/run/tailscale/resolv.conf" } });
    expect(host.paths.get("/etc/resolv.conf.boxpilot-20260929T221804Z")).toEqual({ target: "/run/tailscale/resolv.conf" });
  });

  it("changes nothing unless systemd-resolved runs, has its stub file, and answers", async () => {
    for (const [options, words] of [[{ resolved: "inactive" }, /systemd-resolved is not running/], [{ stubFile: false }, /stub-resolv\.conf does not exist/], [{ stubAnswers: false }, /did not answer for github\.com either/]]) {
      const host = fakeHost(options);
      await expect(restoreNameLookups({}, { ...host, now })).rejects.toThrow(words);
      expect(host.files.symlink).not.toHaveBeenCalled();
      expect(host.files.copyFile).not.toHaveBeenCalled();
      expect(host.paths.get("/etc/resolv.conf")).toEqual({ content: tailscaleFile });
    }
  });

  it("leaves the stub link alone when it is already there, and says so when names still fail", async () => {
    const working = fakeHost({ conf: { target: stubTarget } });
    await expect(restoreNameLookups({}, { ...working, now })).resolves.toMatchObject({ changed: false, alreadyPointed: true });
    expect(working.files.symlink).not.toHaveBeenCalled();
    const failing = fakeHost({ conf: { target: stubTarget }, stubWorks: false });
    await expect(restoreNameLookups({}, { ...failing, now })).rejects.toThrow(/already points at systemd-resolved, and names still do not resolve.*Nothing was changed/);
  });

  it("puts the old file back when names still do not resolve through the stub", async () => {
    const host = fakeHost({ stubWorks: false });
    await expect(restoreNameLookups({}, { ...host, now })).rejects.toThrow(/so the old file was put back \(a copy stays at \/etc\/resolv\.conf\.boxpilot-20260929T221804Z\)/);
    expect(host.paths.get("/etc/resolv.conf")).toEqual({ content: tailscaleFile });
    expect(host.paths.get("/etc/resolv.conf.boxpilot-20260929T221804Z")).toEqual({ content: tailscaleFile });
    // Three tries at the lookup before giving up, each one both names.
    expect(host.run.mock.calls.filter(([binary]) => binary.endsWith("getent"))).toHaveLength(6);
  });

  it("puts a link back as the same link, and nothing back as nothing", async () => {
    const link = fakeHost({ conf: { target: "/run/tailscale/resolv.conf" }, stubWorks: false });
    await expect(restoreNameLookups({}, { ...link, now })).rejects.toThrow(/put back/);
    expect(link.paths.get("/etc/resolv.conf")).toEqual({ target: "/run/tailscale/resolv.conf" });
    const none = fakeHost({ conf: null, stubWorks: false });
    await expect(restoreNameLookups({}, { ...none, now })).rejects.toThrow(/the old state \(no file\) was put back/);
    expect(none.paths.has("/etc/resolv.conf")).toBe(false);
  });

  it("says so when the file cannot be replaced, and leaves it as it was", async () => {
    const host = fakeHost();
    host.files.rename.mockImplementationOnce(async () => { throw Object.assign(new Error("EPERM"), { code: "EPERM" }); });
    await expect(restoreNameLookups({}, { ...host, now })).rejects.toThrow(/could not be replaced \(EPERM\), so it is as it was/);
    expect(host.paths.get("/etc/resolv.conf")).toEqual({ content: tailscaleFile });
    expect([...host.paths.keys()].filter((file) => file.endsWith(".new"))).toEqual([]);
  });
});
