/**
 * Ubuntu Server autoinstall generator (M4.3): renders the `user-data` / `meta-data` pair for
 * an unattended install that boots into a box with BoxPilot already installing itself on first
 * boot. Nothing here touches this host; the only privileged-ish step is hashing the new
 * account's password with openssl (sha512-crypt), and the password is never stored.
 */
import { productVersion } from "./version.mjs";
import { fixedRun } from "./exec.mjs";

const hostnamePattern = /^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$/;
const usernamePattern = /^[a-z_][a-z0-9_-]{0,31}$/;
const sshKeyPattern = /^(ssh-(ed25519|rsa)|ecdsa-sha2-nistp(256|384|521)|sk-(ssh-ed25519|ecdsa-sha2-nistp256)@openssh\.com) [A-Za-z0-9+/=]+( [^\r\n]{0,128})?$/;
const ipv4 = /^(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}$/;
const timezonePattern = /^[A-Za-z_][A-Za-z0-9_+-]*(\/[A-Za-z0-9_+-]+){0,2}$/;
const localePattern = /^[a-z]{2,3}_[A-Z]{2}(\.UTF-8)?$/;
const tagPattern = /^v\d+\.\d+\.\d+(?:-[A-Za-z0-9.]+)?$|^main$|^phase-\d+$/;

export function validateAutoinstallInput(input) {
  const errors = [];
  if (!input || typeof input !== "object" || Array.isArray(input)) return ["An autoinstall request is required"];
  if (typeof input.hostname !== "string" || !hostnamePattern.test(input.hostname)) errors.push("hostname must be lower-case letters, digits, and hyphens");
  if (typeof input.username !== "string" || !usernamePattern.test(input.username) || input.username === "root") errors.push("username must be a Unix user name (not root)");
  if (typeof input.password !== "string" || input.password.length < 12 || input.password.length > 256) errors.push("password must be 12 to 256 characters");
  const keys = Array.isArray(input.sshKeys) ? input.sshKeys : [];
  if (!Array.isArray(input.sshKeys) || keys.length > 20 || keys.some((key) => typeof key !== "string" || !sshKeyPattern.test(key.trim()))) errors.push("sshKeys must be a list of OpenSSH public keys");
  if (!["dhcp", "static"].includes(input.network?.mode)) errors.push("network.mode must be dhcp or static");
  if (input.network?.mode === "static") {
    const cidr = String(input.network.address ?? "").match(/^(.+)\/(\d{1,2})$/);
    if (!cidr || !ipv4.test(cidr[1]) || Number(cidr[2]) < 8 || Number(cidr[2]) > 30) errors.push("network.address must be an IPv4 address with a prefix, like 192.168.1.20/24");
    if (!ipv4.test(String(input.network.gateway ?? ""))) errors.push("network.gateway must be an IPv4 address");
    const dns = Array.isArray(input.network.nameservers) ? input.network.nameservers : [];
    if (!dns.length || dns.length > 3 || dns.some((entry) => !ipv4.test(String(entry)))) errors.push("network.nameservers must list one to three IPv4 addresses");
  }
  if (!["direct", "lvm"].includes(input.disk?.layout)) errors.push("disk.layout must be direct or lvm");
  if (input.timezone !== undefined && (typeof input.timezone !== "string" || !timezonePattern.test(input.timezone))) errors.push("timezone must be an IANA name");
  if (input.locale !== undefined && (typeof input.locale !== "string" || !localePattern.test(input.locale))) errors.push("locale must look like en_US.UTF-8");
  if (input.boxpilotRef !== undefined && (typeof input.boxpilotRef !== "string" || !tagPattern.test(input.boxpilotRef))) errors.push("boxpilotRef must be a release tag like v1.2.3");
  return errors;
}

function yamlString(value) {
  return JSON.stringify(String(value));
}

export async function hashPassword(password, { run = fixedRun } = {}) {
  const result = await run("openssl", ["passwd", "-6", "-stdin"], { timeout: 15_000, input: `${password}\n` });
  const hash = (result.stdout ?? "").trim();
  if (!result.ok || !hash.startsWith("$6$")) throw new Error("Password hashing with openssl failed on this server");
  return hash;
}

export function renderAutoinstall(input, { passwordHash, repository = "AES256Afro/BoxPilot", defaultRef = `v${productVersion}` }) {
  const errors = validateAutoinstallInput(input);
  if (errors.length) throw new Error(errors.join("; "));
  const ref = input.boxpilotRef ?? defaultRef;
  const keys = input.sshKeys.map((key) => key.trim());
  const timezone = input.timezone ?? "Etc/UTC";
  const locale = input.locale ?? "en_US.UTF-8";
  const lines = [
    "#cloud-config",
    "# Generated by BoxPilot. Boot the Ubuntu Server installer with this file as the NoCloud",
    "# user-data (see meta-data alongside it). The install is unattended and ERASES the target disk.",
    "autoinstall:",
    "  version: 1",
    `  locale: ${locale}`,
    "  keyboard:",
    "    layout: us",
    `  timezone: ${timezone}`,
    "  identity:",
    `    hostname: ${input.hostname}`,
    `    username: ${input.username}`,
    `    password: ${yamlString(passwordHash)}`,
    "  ssh:",
    "    install-server: true",
    `    allow-pw: ${keys.length ? "false" : "true"}`,
    ...(keys.length ? ["    authorized-keys:", ...keys.map((key) => `      - ${yamlString(key)}`)] : []),
    "  network:",
    "    version: 2",
    "    ethernets:",
    "      primary:",
    "        match:",
    "          name: \"en*\"",
  ];
  if (input.network.mode === "dhcp") {
    lines.push("        dhcp4: true");
  } else {
    lines.push("        dhcp4: false", "        addresses:", `          - ${input.network.address}`, "        routes:", "          - to: default", `            via: ${input.network.gateway}`, "        nameservers:", "          addresses:", ...input.network.nameservers.map((entry) => `            - ${entry}`));
  }
  lines.push(
    "  storage:",
    "    layout:",
    `      name: ${input.disk.layout}`,
    ...(input.disk.layout === "lvm" ? ["      sizing-policy: all"] : []),
    "  packages:",
    "    - curl",
    "    - ca-certificates",
    "  updates: security",
    "  # First boot of the installed system: install BoxPilot with network and systemd available.",
    "  user-data:",
    "    runcmd:",
    `      - [ sh, -c, ${yamlString(`curl -fsSL https://raw.githubusercontent.com/${repository}/${ref}/scripts/boxpilot-install.sh | sh -s -- --ref ${ref} --access lan --no-token >> /var/log/boxpilot-install.log 2>&1`)} ]`,
    "",
  );
  const metaData = `instance-id: boxpilot-${input.hostname}\nlocal-hostname: ${input.hostname}\n`;
  return { userData: lines.join("\n"), metaData, ref, filename: `${input.hostname}-autoinstall` };
}
