/**
 * Whether this server can look names up the way curl, apt and Docker do (2026-09-29).
 *
 * After a power cut the owner's server came back with every lookup failing: the BoxPilot upgrade
 * stopped at "Could not resolve host: raw.githubusercontent.com" and an app update failed pulling
 * its image. At boot tailscaled mistook systemd-resolved's resolvconf shim for openresolv, could not
 * read the OS's DNS settings ("Tailscale failed to fetch the DNS configuration of your device: exit
 * status 1"), and /etc/resolv.conf was left a plain file sending every lookup to 100.100.100.100,
 * which answered nothing. systemd-resolved was running and fine the whole time - `resolvectl query`
 * worked - but nothing asked it: /etc/resolv.conf was no longer its stub link. Linking it back
 * (../run/systemd/resolve/stub-resolv.conf) fixed every lookup at once, without a Tailscale restart.
 *
 * Read in the web service, unprivileged: getent (NSS, which is what curl and Docker use), the link
 * target of /etc/resolv.conf, `systemctl is-active`, a DNS query to resolved's stub address, and
 * Tailscale's own status. The helper cannot do this: it runs with PrivateNetwork=true. Nothing here
 * depends on ping, dig or tcpdump, which an Ubuntu 26.04 server may not have.
 *
 * A healthy server costs two getent calls and a readlink; the rest is asked only once lookups fail.
 */
import { Resolver } from "node:dns/promises";
import { readFile, readlink, stat } from "node:fs/promises";
import net from "node:net";
import { fixedRun } from "./exec.mjs";

/** Two names on different operators, both of which BoxPilot needs: its releases, and app images. */
export const lookupNames = Object.freeze(["github.com", "registry-1.docker.io"]);
export const resolvConfPath = "/etc/resolv.conf";
export const stubFile = "/run/systemd/resolve/stub-resolv.conf";
/** What Ubuntu's own /etc/resolv.conf link says, relative, as systemd ships it. */
export const stubLinkTarget = "../run/systemd/resolve/stub-resolv.conf";
/** Where tailscaled's "direct" mode keeps the file it replaced. */
export const tailscaleBackupPath = "/etc/resolv.pre-tailscale-backup.conf";
export const stubAddress = "127.0.0.53";
/** Tailscale's own resolver, which a file it wrote points at. */
export const tailscaleResolver = "100.100.100.100";
/** Addresses reached over TCP when names fail, to tell "DNS is broken" from "the internet is gone". */
export const internetProbes = Object.freeze([{ host: "1.1.1.1", port: 443 }, { host: "9.9.9.9", port: 443 }]);

const binaries = {
  getent: "/usr/bin/getent",
  systemctl: process.env.BOXPILOT_SYSTEMCTL_BINARY ?? "/usr/bin/systemctl",
  resolvectl: "/usr/bin/resolvectl",
  tailscale: process.env.BOXPILOT_TAILSCALE_BINARY ?? "/usr/bin/tailscale",
};

/** Whether a link target is systemd-resolved's stub file, however it is spelled. */
export function isStubTarget(target) {
  if (typeof target !== "string" || !target) return false;
  const resolved = target.startsWith("/") ? target : `/etc/${target}`;
  const parts = [];
  for (const part of resolved.split("/")) {
    if (!part || part === ".") continue;
    if (part === "..") parts.pop(); else parts.push(part);
  }
  return `/${parts.join("/")}` === stubFile;
}

/** The nameservers and search domains a resolv.conf names, and who says they wrote it. */
export function parseResolvConf(text) {
  const nameservers = [];
  const search = [];
  let generatedBy = null;
  for (const raw of String(text ?? "").split("\n")) {
    const line = raw.trim();
    if (/^#.*generated by tailscale/i.test(line) || /tailscale\.com\/s\/resolvconf-overwrite/i.test(line)) generatedBy ??= "tailscale";
    else if (/^#.*systemd-resolved/i.test(line)) generatedBy ??= "systemd-resolved";
    else if (/^#.*generated by resolvconf/i.test(line)) generatedBy ??= "resolvconf";
    else if (/^#.*NetworkManager/i.test(line)) generatedBy ??= "NetworkManager";
    const match = line.match(/^(nameserver|search|domain)\s+(.+)$/);
    if (!match) continue;
    if (match[1] === "nameserver") nameservers.push(match[2].split(/\s+/)[0]);
    else search.push(...match[2].split(/\s+/));
  }
  return { nameservers, search, generatedBy };
}

/** `tailscale status --json` and `tailscale debug prefs`, reduced to what bears on DNS. */
export function parseTailscaleDns({ status = null, prefs = null } = {}) {
  const read = (text) => { try { return text ? JSON.parse(text) : null; } catch { return null; } };
  const parsedStatus = read(status);
  const parsedPrefs = read(prefs);
  if (!parsedStatus && !parsedPrefs) return null;
  const health = Array.isArray(parsedStatus?.Health) ? parsedStatus.Health.filter((entry) => typeof entry === "string") : [];
  return {
    running: parsedStatus ? parsedStatus.BackendState === "Running" : null,
    // "Use Tailscale DNS settings" (tailscale set --accept-dns): whether it manages this server's DNS at all.
    acceptDns: typeof parsedPrefs?.CorpDNS === "boolean" ? parsedPrefs.CorpDNS : null,
    dnsWarnings: health.filter((entry) => /\bDNS\b/i.test(entry)).map((entry) => entry.slice(0, 300)),
  };
}

/** The addresses in `getent ahosts` output, first column, once each. */
export function parseGetent(stdout) {
  return [...new Set(String(stdout ?? "").split("\n").map((line) => line.trim().split(/\s+/)[0]).filter((address) => net.isIP(address)))];
}

/** One name through NSS, as curl and Docker would look it up. */
export async function nssLookup(run, name, { timeoutMs = 12_000 } = {}) {
  const result = await Promise.resolve().then(() => run(binaries.getent, ["ahosts", name], { timeout: timeoutMs })).catch((error) => ({ ok: false, code: null, stderr: error.message }));
  const addresses = result.ok ? parseGetent(result.stdout) : [];
  if (addresses.length) return { name, ok: true, addresses: addresses.slice(0, 4), error: null };
  // getent: 2 is "not found", which is what a resolver that answers nothing looks like too.
  const error = result.timedOut ? "timed out" : result.code === 2 ? "no answer" : /ENOENT|not found/i.test(String(result.stderr ?? "")) && result.code === null ? "unavailable" : `failed${result.code !== null && result.code !== undefined ? ` (exit ${result.code})` : ""}`;
  return { name, ok: false, addresses: [], error };
}

/** One name asked of a DNS server directly, as a laptop pointed at it would. */
export async function askServer(address, name, { timeoutMs = 4000 } = {}) {
  const resolver = new Resolver({ timeout: timeoutMs, tries: 1 });
  resolver.setServers([address]);
  try {
    const addresses = await resolver.resolve4(name);
    return { ok: addresses.length > 0, addresses: addresses.slice(0, 4), error: addresses.length ? null : "no address" };
  } catch (error) {
    return { ok: false, addresses: [], error: String(error?.code ?? error?.message ?? error) };
  } finally {
    resolver.cancel();
  }
}

/** Whether a TCP connection opens, without sending anything. */
export function tcpReach({ host, port }, { timeoutMs = 3000 } = {}) {
  return new Promise((resolve) => {
    const socket = net.connect({ host, port });
    const done = (ok) => { socket.destroy(); resolve(ok); };
    socket.setTimeout(timeoutMs, () => done(false));
    socket.once("connect", () => done(true));
    socket.once("error", () => done(false));
  });
}

const defaultFiles = {
  readlink: (file) => readlink(file),
  readFile: (file) => readFile(file, "utf8"),
  isFile: (file) => stat(file).then((info) => info.isFile(), () => false),
};

/** What /etc/resolv.conf is: the stub link, another link, a plain file, or nothing. */
export async function describeResolvConf(files = defaultFiles) {
  const link = await files.readlink(resolvConfPath).then((target) => ({ kind: "link", target }), (error) => ({ kind: error?.code === "EINVAL" ? "file" : error?.code === "ENOENT" ? "missing" : "unknown", target: null }));
  return { ...link, stub: link.kind === "link" && isStubTarget(link.target) };
}

/**
 * Everything Repair needs to say why names fail and whether pointing lookups back at
 * systemd-resolved would fix it. Null off Linux (a development machine), where none of it applies.
 *
 * `dnsServer` is the DNS app on this server the rest of the house uses (Pi-hole, AdGuard Home), if
 * any: { name, address, running }. It is asked directly, so the finding can say whether the home
 * network's DNS is separate and fine.
 */
export async function inspectNameLookups({ run = fixedRun, files = defaultFiles, ask = askServer, reach = tcpReach, dnsServer = null, platform = process.platform, now = () => new Date() } = {}) {
  if (platform !== "linux") return null;
  const [names, resolvConf] = await Promise.all([Promise.all(lookupNames.map((name) => nssLookup(run, name))), describeResolvConf(files)]);
  const base = { available: true, checkedAt: now().toISOString(), names, nssWorks: names.some((entry) => entry.ok), resolvConf };
  if (base.nssWorks) return base;
  if (names.every((entry) => entry.error === "unavailable")) return { available: false, reason: "getent is not installed", names, nssWorks: false, resolvConf };
  // Only now, with every name failing: the rest of the picture, all at once.
  const quiet = (promise, fallback = null) => Promise.resolve().then(() => promise).catch(() => fallback);
  // A getter, so the caller's slower reads (which app is the DNS server) wait until they matter.
  if (typeof dnsServer === "function") dnsServer = await quiet(dnsServer());
  const [content, active, stubPresent, stub, resolvectl, status, prefs, tailscaleBackup, internet, server] = await Promise.all([
    quiet(files.readFile(resolvConfPath)),
    quiet(run(binaries.systemctl, ["is-active", "systemd-resolved.service"], { timeout: 10_000 })),
    quiet(files.isFile(stubFile), false),
    quiet(ask(stubAddress, lookupNames[0]), { ok: false, addresses: [], error: "failed" }),
    // resolved itself, not its listener: tells a stub turned off (DNSStubListener=no) from a resolved that cannot resolve.
    quiet(run(binaries.resolvectl, ["query", "--legend=no", lookupNames[0]], { timeout: 12_000 })),
    quiet(run(binaries.tailscale, ["status", "--json", "--peers=false"], { timeout: 10_000, maxBuffer: 4 * 1024 * 1024 })),
    quiet(run(binaries.tailscale, ["debug", "prefs"], { timeout: 10_000 })),
    quiet(files.readlink(tailscaleBackupPath)),
    quiet(Promise.all(internetProbes.map((probe) => reach(probe))), []),
    dnsServer?.address && dnsServer.running !== false ? quiet(ask(dnsServer.address, "example.com"), { ok: false, addresses: [], error: "failed" }) : null,
  ]);
  const parsed = parseResolvConf(content);
  return {
    ...base,
    resolvConf: { ...resolvConf, nameservers: parsed.nameservers.slice(0, 6), generatedBy: parsed.generatedBy, tailscaleBackup: typeof tailscaleBackup === "string" ? tailscaleBackup : null },
    resolved: {
      active: String(active?.stdout ?? "").trim() === "active",
      stubPresent: stubPresent === true,
      stubAnswers: stub,
      // Null when resolvectl could not be asked at all (not installed), rather than "cannot resolve".
      resolves: !resolvectl || (!resolvectl.ok && resolvectl.code === null && /ENOENT/.test(String(resolvectl.stderr ?? ""))) ? null : Boolean(resolvectl.ok),
    },
    tailscale: parseTailscaleDns({ status: status?.ok ? status.stdout : null, prefs: prefs?.ok ? prefs.stdout : null }),
    internet: { reachable: Array.isArray(internet) && internet.some(Boolean), probes: internetProbes.map((probe, index) => ({ ...probe, ok: Boolean(internet?.[index]) })) },
    dnsServer: dnsServer ? { name: dnsServer.name, address: dnsServer.address ?? null, running: dnsServer.running !== false, answers: server ? Boolean(server.ok) : null } : null,
  };
}

/**
 * Why names fail, and whether pointing /etc/resolv.conf back at systemd-resolved fixes it. Pure.
 * Null when there is nothing to say: lookups work, or they could not be checked.
 *
 * - `repoint`: resolv.conf is not the stub link, resolved is running, its stub file exists and its
 *   stub answers. This is the owner's case, and the one the fix is offered for.
 * - `stub-off`: resolved resolves, but nothing answers on 127.0.0.53 (DNSStubListener=no, which a
 *   Pi-hole install on the host often sets), so the stub link would not help.
 * - `upstream`: resolved is what lookups go through, or would be, and it cannot resolve either:
 *   the router or the internet connection, not this server's settings.
 * - `no-resolved`: systemd-resolved is not running here, or has no stub file, so there is nothing
 *   to point lookups back at.
 * - `other`: the stub link is in place and resolved answers, yet lookups through NSS fail.
 */
export function nameLookupVerdict(facts) {
  if (!facts?.available || facts.nssWorks !== false) return null;
  const conf = facts.resolvConf ?? {};
  const resolved = facts.resolved ?? {};
  const stubAnswers = resolved.stubAnswers?.ok === true;
  const tailscaleWrote = !conf.stub && (conf.generatedBy === "tailscale" || (conf.nameservers ?? []).includes(tailscaleResolver) || Boolean(conf.tailscaleBackup));
  const common = { tailscaleWrote, internet: facts.internet?.reachable ?? null };
  if (!resolved.active || !resolved.stubPresent) return { kind: "no-resolved", ...common };
  if (!conf.stub && stubAnswers) return { kind: "repoint", ...common };
  if (!stubAnswers && resolved.resolves === true) return { kind: "stub-off", ...common };
  if (!stubAnswers) return { kind: "upstream", ...common };
  return { kind: "other", ...common };
}
