import { describe, expect, it, vi } from "vitest";
import { inspectNameLookups, isStubTarget, nameLookupVerdict, parseGetent, parseResolvConf, parseTailscaleDns } from "./name-lookups.mjs";

// What the owner's server said on 2026-09-29, after the power cut: Tailscale's file in place of the
// stub link, and Tailscale's own health warning. Addresses are documentation placeholders.
const tailscaleFile = "# resolv.conf(5) file generated by tailscale\n# For more info, see https://tailscale.com/s/resolvconf-overwrite\n# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN\n\nnameserver 100.100.100.100\nsearch tail0a1b.ts.net\n";
const tailscaleStatus = JSON.stringify({ BackendState: "Running", Health: ["Tailscale failed to fetch the DNS configuration of your device: exit status 1", "Some peers are advertising routes but --accept-routes is false"] });

describe("reading /etc/resolv.conf and Tailscale", () => {
  it("knows systemd-resolved's stub link however it is spelled", () => {
    expect(isStubTarget("../run/systemd/resolve/stub-resolv.conf")).toBe(true);
    expect(isStubTarget("/run/systemd/resolve/stub-resolv.conf")).toBe(true);
    expect(isStubTarget("/etc/../run/systemd/resolve/./stub-resolv.conf")).toBe(true);
    // resolved's other file lists the real servers: a working setup, but not the stub.
    expect(isStubTarget("../run/systemd/resolve/resolv.conf")).toBe(false);
    expect(isStubTarget(null)).toBe(false);
  });

  it("names the servers in a file and who wrote it", () => {
    expect(parseResolvConf(tailscaleFile)).toEqual({ nameservers: ["100.100.100.100"], search: ["tail0a1b.ts.net"], generatedBy: "tailscale" });
    expect(parseResolvConf("# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).\nnameserver 127.0.0.53\noptions edns0 trust-ad\n")).toMatchObject({ nameservers: ["127.0.0.53"], generatedBy: "systemd-resolved" });
    expect(parseResolvConf("")).toEqual({ nameservers: [], search: [], generatedBy: null });
  });

  it("keeps only Tailscale's DNS warnings, and whether it manages DNS at all", () => {
    expect(parseTailscaleDns({ status: tailscaleStatus, prefs: JSON.stringify({ CorpDNS: true }) })).toEqual({
      running: true, acceptDns: true, dnsWarnings: ["Tailscale failed to fetch the DNS configuration of your device: exit status 1"],
    });
    expect(parseTailscaleDns({ status: "not json", prefs: null })).toBeNull();
  });

  it("reads getent's addresses once each", () => {
    expect(parseGetent("140.82.121.4    STREAM github.com\n140.82.121.4    DGRAM  \n140.82.121.4    RAW    \n")).toEqual(["140.82.121.4"]);
    expect(parseGetent("")).toEqual([]);
  });
});

/** A run() that answers each binary the way the owner's server did. */
function hostRun({ getent = "fail", resolved = "active", resolvectl = true, tailscale = true } = {}) {
  return vi.fn(async (binary, args) => {
    const name = binary.split("/").pop();
    if (name === "getent") {
      if (getent === "ok") return { ok: true, code: 0, stdout: `192.0.2.10 STREAM ${args[1]}\n192.0.2.10 DGRAM\n`, stderr: "" };
      if (getent === "missing") return { ok: false, code: null, stdout: "", stderr: "spawn /usr/bin/getent ENOENT" };
      return { ok: false, code: 2, stdout: "", stderr: "" };
    }
    if (name === "systemctl") return { ok: resolved === "active", code: resolved === "active" ? 0 : 3, stdout: resolved, stderr: "" };
    if (name === "resolvectl") return resolvectl ? { ok: true, code: 0, stdout: "github.com: 192.0.2.10", stderr: "" } : { ok: false, code: 1, stdout: "", stderr: "resolve call failed" };
    if (name === "tailscale" && args[0] === "status") return tailscale ? { ok: true, code: 0, stdout: tailscaleStatus, stderr: "" } : { ok: false, code: null, stdout: "", stderr: "spawn ENOENT" };
    if (name === "tailscale" && args[0] === "debug") return tailscale ? { ok: true, code: 0, stdout: JSON.stringify({ CorpDNS: true }), stderr: "" } : { ok: false, code: null, stdout: "", stderr: "" };
    throw new Error(`unexpected ${binary}`);
  });
}

function hostFiles({ conf = { kind: "file", content: tailscaleFile }, stub = true, backup = "../run/systemd/resolve/stub-resolv.conf" } = {}) {
  const error = (code) => Object.assign(new Error(code), { code });
  return {
    readlink: vi.fn(async (file) => {
      if (file === "/etc/resolv.conf") { if (conf.kind === "link") return conf.target; throw error(conf.kind === "missing" ? "ENOENT" : "EINVAL"); }
      if (file === "/etc/resolv.pre-tailscale-backup.conf" && backup) return backup;
      throw error("ENOENT");
    }),
    readFile: vi.fn(async () => { if (conf.kind === "missing") throw error("ENOENT"); return conf.content ?? ""; }),
    isFile: vi.fn(async () => stub),
  };
}

describe("inspectNameLookups", () => {
  it("costs two getent calls and a readlink on a healthy server, and asks nothing else", async () => {
    const run = hostRun({ getent: "ok" });
    const files = hostFiles({ conf: { kind: "link", target: "../run/systemd/resolve/stub-resolv.conf" } });
    const ask = vi.fn();
    const reach = vi.fn();
    const facts = await inspectNameLookups({ run, files, ask, reach, platform: "linux", dnsServer: vi.fn() });
    expect(facts).toMatchObject({ available: true, nssWorks: true, resolvConf: { kind: "link", stub: true } });
    expect(run.mock.calls.map(([binary, args]) => `${binary.split("/").pop()} ${args.join(" ")}`)).toEqual(["getent ahosts github.com", "getent ahosts registry-1.docker.io"]);
    expect(files.readFile).not.toHaveBeenCalled();
    expect(ask).not.toHaveBeenCalled();
    expect(reach).not.toHaveBeenCalled();
  });

  it("reads the owner's server after the power cut: Tailscale's file, resolved fine, Pi-hole fine", async () => {
    const ask = vi.fn(async (address) => (address === "127.0.0.53" ? { ok: true, addresses: ["192.0.2.10"], error: null } : { ok: true, addresses: ["192.0.2.20"], error: null }));
    const dnsServer = vi.fn(async () => ({ name: "Pi-hole", address: "127.0.0.1", running: true }));
    const facts = await inspectNameLookups({ run: hostRun(), files: hostFiles(), ask, reach: async () => true, platform: "linux", dnsServer, now: () => new Date("2026-09-29T22:30:00Z") });
    expect(facts).toMatchObject({
      available: true, nssWorks: false,
      names: [{ name: "github.com", ok: false, error: "no answer" }, { name: "registry-1.docker.io", ok: false, error: "no answer" }],
      resolvConf: { kind: "file", stub: false, nameservers: ["100.100.100.100"], generatedBy: "tailscale", tailscaleBackup: "../run/systemd/resolve/stub-resolv.conf" },
      resolved: { active: true, stubPresent: true, stubAnswers: { ok: true }, resolves: true },
      tailscale: { running: true, acceptDns: true, dnsWarnings: ["Tailscale failed to fetch the DNS configuration of your device: exit status 1"] },
      internet: { reachable: true },
      dnsServer: { name: "Pi-hole", address: "127.0.0.1", running: true, answers: true },
    });
    expect(ask).toHaveBeenCalledWith("127.0.0.53", "github.com");
    expect(ask).toHaveBeenCalledWith("127.0.0.1", "example.com");
    expect(nameLookupVerdict(facts)).toEqual({ kind: "repoint", tailscaleWrote: true, internet: true });
  });

  it("says it could not check when getent is not there, and is not asked off Linux", async () => {
    const missing = await inspectNameLookups({ run: hostRun({ getent: "missing" }), files: hostFiles(), platform: "linux" });
    expect(missing).toMatchObject({ available: false, nssWorks: false });
    expect(nameLookupVerdict(missing)).toBeNull();
    expect(await inspectNameLookups({ run: hostRun(), files: hostFiles(), platform: "win32" })).toBeNull();
  });

  it("leaves a stopped DNS app unasked", async () => {
    const ask = vi.fn(async () => ({ ok: true, addresses: ["192.0.2.10"], error: null }));
    const facts = await inspectNameLookups({ run: hostRun(), files: hostFiles(), ask, reach: async () => true, platform: "linux", dnsServer: async () => ({ name: "Pi-hole", address: "127.0.0.1", running: false }) });
    expect(facts.dnsServer).toEqual({ name: "Pi-hole", address: "127.0.0.1", running: false, answers: null });
    expect(ask).toHaveBeenCalledTimes(1);
  });
});

describe("nameLookupVerdict", () => {
  const broken = (overrides = {}) => ({
    available: true, nssWorks: false, names: [{ name: "github.com", ok: false, addresses: [], error: "no answer" }],
    resolvConf: { kind: "file", stub: false, nameservers: ["100.100.100.100"], generatedBy: "tailscale", tailscaleBackup: null },
    resolved: { active: true, stubPresent: true, stubAnswers: { ok: true, addresses: ["192.0.2.10"] }, resolves: true },
    internet: { reachable: true, probes: [] },
    ...overrides,
  });
  it("says nothing when lookups work or could not be checked", () => {
    expect(nameLookupVerdict(null)).toBeNull();
    expect(nameLookupVerdict({ available: true, nssWorks: true })).toBeNull();
    expect(nameLookupVerdict({ available: false })).toBeNull();
  });
  it("offers pointing lookups back only when resolved runs, has its stub, and answers", () => {
    expect(nameLookupVerdict(broken()).kind).toBe("repoint");
    // Nothing at all at /etc/resolv.conf is the same fix.
    expect(nameLookupVerdict(broken({ resolvConf: { kind: "missing", stub: false, nameservers: [] } }))).toMatchObject({ kind: "repoint", tailscaleWrote: false });
    expect(nameLookupVerdict(broken({ resolved: { active: false, stubPresent: true, stubAnswers: { ok: true } } })).kind).toBe("no-resolved");
    expect(nameLookupVerdict(broken({ resolved: { active: true, stubPresent: false, stubAnswers: { ok: true } } })).kind).toBe("no-resolved");
  });
  it("tells a stub turned off from a resolved that cannot resolve, and both from a dead connection", () => {
    expect(nameLookupVerdict(broken({ resolved: { active: true, stubPresent: true, stubAnswers: { ok: false, error: "ECONNREFUSED" }, resolves: true } })).kind).toBe("stub-off");
    expect(nameLookupVerdict(broken({ resolved: { active: true, stubPresent: true, stubAnswers: { ok: false, error: "ETIMEOUT" }, resolves: false } }))).toMatchObject({ kind: "upstream", internet: true });
    expect(nameLookupVerdict(broken({ resolvConf: { kind: "link", stub: true, nameservers: ["127.0.0.53"] }, resolved: { active: true, stubPresent: true, stubAnswers: { ok: false }, resolves: false }, internet: { reachable: false, probes: [] } }))).toMatchObject({ kind: "upstream", internet: false, tailscaleWrote: false });
    expect(nameLookupVerdict(broken({ resolvConf: { kind: "link", stub: true, nameservers: ["127.0.0.53"] } })).kind).toBe("other");
  });
});
