#!/bin/bash
# A server that cannot look names up, on a real host (2026-09-29): /etc/resolv.conf replaced the
# way Tailscale left it on the owner's server after a power cut, Repair's reading of it made as the
# web service makes it (unprivileged), and the fix run through boxpilot-run@.service as shipped.
#
#   sudo bash tests/ubuntu/name-lookups.sh /path/to/node-24
#
# DISPOSABLE MACHINES ONLY (CI runs it on GitHub's Ubuntu VMs): it replaces /etc/resolv.conf, edits
# /etc/nsswitch.conf, stops systemd-resolved for a moment and installs boxpilot-run@.service. It puts
# resolv.conf, nsswitch.conf and systemd-resolved back as they were when it ends.
#
#   0. A healthy runner: names resolve through NSS, and Repair finds nothing.
#   1. Tailscale's file in place of the stub link: getent fails while resolvectl still answers, and
#      Repair says so and offers "Point name lookups back to systemd-resolved".
#   2. The fix: it keeps the file, links the stub, and getent works again at once. A second run
#      changes nothing.
#   3. When lookups still fail through the stub (NSS told not to ask DNS), the old file goes back.
#   4. With systemd-resolved stopped there is nothing to point at: nothing changes, and Repair
#      explains without offering the fix.
set -uo pipefail

[ "$(id -u)" -eq 0 ] || { echo "run as root, on a disposable machine" >&2; exit 2; }
NODE="${1:-$(command -v node || true)}"
[ -x "$NODE" ] && [ "$("$NODE" -p 'process.versions.node.split(".")[0]')" -ge 24 ] || { echo "pass a Node.js 24 binary as the first argument" >&2; exit 2; }
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
STUB=../run/systemd/resolve/stub-resolv.conf
WORK="$(mktemp -d /var/tmp/bp-names.XXXXXX)"
FAILURES=0
RESULTS=""

section() { printf '\n==== %s ====\n' "$*"; }
note() { printf '    %s\n' "$*"; }
record() { # record PASS|FAIL <what>
  RESULTS="${RESULTS}$1  $2"$'\n'
  printf '  %s  %s\n' "$1" "$2"
  [ "$1" = PASS ] || FAILURES=$((FAILURES + 1))
}
check() { # check <what> <command...>
  local what="$1"; shift
  if "$@"; then record PASS "$what"; else record FAIL "$what"; fi
}
contains() { case "$1" in *"$2"*) return 0 ;; *) return 1 ;; esac; }
field() { "$NODE" -p "const value = JSON.parse(process.argv[1]); String(value.${1})" "$2"; }
# Repair's reading, made as the web service makes it: as an unprivileged user.
inspect() { OUT="$(runuser -u nobody -- "$NODE" /opt/boxpilot/tests/name-lookups.mjs inspect /opt/boxpilot/server 2>&1 | tail -n 1)"; }
restore() { OUT="$("$NODE" /opt/boxpilot/tests/name-lookups.mjs restore /opt/boxpilot/server 2>&1 | tail -n 1)"; }
resolves() { timeout 20 getent hosts github.com >/dev/null; }
tailscale_file() {
  rm -f /etc/resolv.conf
  cp "${WORK}/tailscale.conf" /etc/resolv.conf
  chmod 644 /etc/resolv.conf
}

cleanup() {
  systemctl unmask --runtime systemd-resolved.service >/dev/null 2>&1
  systemctl start systemd-resolved.service 2>/dev/null
  [ -f "${WORK}/nsswitch.conf" ] && cp "${WORK}/nsswitch.conf" /etc/nsswitch.conf
  [ -e "${WORK}/resolv.conf" ] || [ -L "${WORK}/resolv.conf" ] && cp -P --remove-destination "${WORK}/resolv.conf" /etc/resolv.conf
  rm -f /etc/resolv.conf.boxpilot-* /etc/resolv.pre-tailscale-backup.conf /etc/.resolv.conf.boxpilot-*
  rm -rf "$WORK"
}
trap cleanup EXIT

section "Prepare: $(. /etc/os-release && echo "$PRETTY_NAME"), $(systemctl --version | head -n 1)"
cp -P /etc/resolv.conf "${WORK}/resolv.conf"
cp /etc/nsswitch.conf "${WORK}/nsswitch.conf"
note "/etc/resolv.conf -> $(readlink /etc/resolv.conf || echo 'a plain file')"
note "nsswitch: $(grep '^hosts:' /etc/nsswitch.conf)"
note "systemd-resolved: $(systemctl is-active systemd-resolved.service)"
if [ "$(readlink /etc/resolv.conf)" != "$STUB" ] || [ "$(systemctl is-active systemd-resolved.service)" != active ]; then
  record FAIL "the runner uses systemd-resolved's stub, as a stock Ubuntu server does"
  printf '%s' "$RESULTS"; exit 1
fi
# The server, and boxpilot-run@.service as shipped but for where node is.
install -d -m 0755 /opt/boxpilot /opt/boxpilot/tests
cp -r "${ROOT}/server" "${ROOT}/scripts" "${ROOT}/package.json" /opt/boxpilot/
cp "${ROOT}/tests/ubuntu/name-lookups.mjs" /opt/boxpilot/tests/
chmod -R a+rX /opt/boxpilot
sed -e "s|/usr/local/bin/node|${NODE}|g" "${ROOT}/deploy/boxpilot-run@.service" > /etc/systemd/system/boxpilot-run@.service
install -d -m 0700 /run/boxpilot /run/boxpilot/run
systemctl daemon-reload
# The file tailscaled wrote on the owner's server; one-second tries so a dead resolver fails fast.
printf '# resolv.conf(5) file generated by tailscale\n# For more info, see https://tailscale.com/s/resolvconf-overwrite\n# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN\n\nnameserver 100.100.100.100\nsearch tail0a1b.ts.net\noptions timeout:1 attempts:1\n' > "${WORK}/tailscale.conf"

section "0. A healthy runner"
inspect
note "reading: $(field 'facts.names.map((entry) => `${entry.name}: ${entry.ok ? entry.addresses[0] : entry.error}`).join("; ")' "$OUT")"
check "it is read as an unprivileged user" [ "$(field uid "$OUT")" != 0 ]
check "names resolve through NSS" [ "$(field facts.nssWorks "$OUT")" = true ]
check "and Repair finds nothing" [ "$(field 'findings.length' "$OUT")" = 0 ]

section "1. Tailscale's file in place of the stub link"
tailscale_file
ln -s "$STUB" /etc/resolv.pre-tailscale-backup.conf
note "$(grep nameserver /etc/resolv.conf)"
check "getent hosts github.com fails, as curl and Docker did" bash -c '! timeout 20 getent hosts github.com >/dev/null'
check "while resolvectl query still answers" resolvectl query github.com
inspect
note "verdict: $(field 'JSON.stringify(verdict)' "$OUT")"
check "Repair calls it the owner's case" [ "$(field verdict.kind "$OUT")" = repoint ]
check "and says Tailscale wrote the file" [ "$(field verdict.tailscaleWrote "$OUT")" = true ]
check "with the finding the owner needed" [ "$(field finding.title "$OUT")" = "homebox cannot look up website names, so updates and app downloads fail" ]
check "and its fix" [ "$(field finding.fix.operationId "$OUT")" = dns.lookups.restore ]
note "detail: $(field finding.detail "$OUT")"

section "2. Point name lookups back to systemd-resolved, through boxpilot-run@"
restore
note "result: ${OUT}"
check "the task succeeded" [ "$(field ok "$OUT")" = true ]
check "and changed the file" [ "$(field result.changed "$OUT")" = true ]
check "/etc/resolv.conf is the stub link again" [ "$(readlink /etc/resolv.conf)" = "$STUB" ]
check "getent hosts github.com works at once" resolves
BACKUP="$(field result.backup "$OUT")"
check "the replaced file is kept as ${BACKUP}" cmp -s "$BACKUP" "${WORK}/tailscale.conf"
check "no temporary file is left behind" bash -c '! ls /etc/.resolv.conf.boxpilot-* >/dev/null 2>&1'
inspect
check "and Repair finds nothing now" [ "$(field 'findings.length' "$OUT")" = 0 ]
restore
check "run again, it changes nothing" [ "$(field result.alreadyPointed "$OUT")" = true ]

section "3. Lookups that still fail through the stub put the old file back"
tailscale_file
sed -i 's/^hosts:.*/hosts: files/' /etc/nsswitch.conf
note "nsswitch: $(grep '^hosts:' /etc/nsswitch.conf) (NSS never asks DNS now)"
restore
note "result: ${OUT}"
check "the task failed" [ "$(field ok "$OUT")" = false ]
check "saying the old file was put back" contains "$(field error "$OUT")" "so the old file was put back"
check "/etc/resolv.conf is Tailscale's file again, not a link" bash -c '[ ! -L /etc/resolv.conf ] && cmp -s /etc/resolv.conf "$1"' _ "${WORK}/tailscale.conf"
cp "${WORK}/nsswitch.conf" /etc/nsswitch.conf

section "4. With systemd-resolved stopped, nothing to point at"
# Masked for the moment, or the resolvectl query Repair makes would start it again over D-Bus.
systemctl mask --runtime systemd-resolved.service >/dev/null 2>&1
systemctl stop systemd-resolved.service
restore
note "result: ${OUT}"
check "the task refuses" contains "$(field error "$OUT")" "systemd-resolved is not running"
check "and changes nothing" bash -c '[ ! -L /etc/resolv.conf ] && cmp -s /etc/resolv.conf "$1"' _ "${WORK}/tailscale.conf"
inspect
note "verdict: $(field 'JSON.stringify(verdict)' "$OUT")"
check "Repair still says names fail" [ "$(field finding.id "$OUT")" = name-lookups ]
check "because there is no systemd-resolved to point at" [ "$(field verdict.kind "$OUT")" = no-resolved ]
check "without offering the fix" [ "$(field 'finding.fixes.length' "$OUT")" = 0 ]
check "and says what to do instead" contains "$(field finding.manual "$OUT")" "sudo systemctl restart tailscaled"
systemctl unmask --runtime systemd-resolved.service >/dev/null 2>&1
systemctl start systemd-resolved.service

section "Summary"
printf '%s' "$RESULTS"
[ "$FAILURES" -eq 0 ] && echo "All checks passed." || echo "${FAILURES} check(s) failed."
exit "$FAILURES"
